schema_version = "1.0.0"

id = "blender_cnc_toolkit_eevee_next"
version = "0.2.1"
name = "Blender C&C Toolkit (Eevee Next)"
tagline = "All-in-one toolkit to render C&C assets."
maintainer = "Zawaro <zawaroarts@gmail.com>"
type = "add-on"
license = [
  "SPDX:GPL-3.0-or-later",
]

permissions = ["files"]

blender_version_min = "4.2.0"
